import fs from 'fs';
import path from 'path';
import { fetchWsAllowlistFromGithub } from './ws-allowlist-github';
import { fetchWsAllowlistFromSite } from './ws-allowlist-site';
import type { WsSkinAllowEntry } from './ws-weapons-config';
import { clearWsWeaponsAllowlistCache } from './ws-weapons-config';
import { getSourceModRoots } from './weapons-db-path';

function mergeEntries(
  base: WsSkinAllowEntry[],
  extra: WsSkinAllowEntry[],
): WsSkinAllowEntry[] {
  const map = new Map<string, WsSkinAllowEntry>();
  for (const entry of base) {
    map.set(`${entry.weaponId}:${entry.paintkit}`, entry);
  }
  for (const entry of extra) {
    map.set(`${entry.weaponId}:${entry.paintkit}`, entry);
  }
  return [...map.values()];
}

function buildWeaponsCfgContent(entries: WsSkinAllowEntry[]): string {
  const lines: string[] = [
    '// Generated by api-csgo — kgns weapons + clutchclube catalog (admin skins)',
    '"Skins"',
    '{',
  ];

  for (const entry of entries) {
    const safeName = entry.name.replace(/"/g, "'").slice(0, 120);
    const weaponClass = entry.weaponId.endsWith(';')
      ? entry.weaponId
      : `${entry.weaponId};`;
    lines.push(`\t"${safeName}"`);
    lines.push('\t{');
    lines.push(`\t\t"index"\t\t"${entry.paintkit}"`);
    lines.push(`\t\t"classes"\t\t"${weaponClass}"`);
    lines.push('\t}');
  }

  lines.push('}');
  return `${lines.join('\n')}\n`;
}

function resolveWeaponsCfgPath(lang: string): string | null {
  for (const root of getSourceModRoots()) {
    const cfgPath = path.join(
      root,
      'addons/sourcemod/configs/weapons',
      `weapons_${lang}.cfg`,
    );
    const dir = path.dirname(cfgPath);
    if (fs.existsSync(dir)) {
      return cfgPath;
    }
  }
  return null;
}

export async function syncWeaponsCfgFromSite(): Promise<{
  ok: boolean;
  path: string | null;
  count: number;
  siteCount: number;
  error?: string;
}> {
  const lang = process.env.WS_WEAPONS_LANG?.trim() || 'english';

  try {
    const base = await fetchWsAllowlistFromGithub(lang);
    let siteEntries: WsSkinAllowEntry[] = [];
    try {
      siteEntries = await fetchWsAllowlistFromSite();
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`[weapons-cfg] site allowlist fetch failed: ${message}`);
    }

    const merged = mergeEntries(base, siteEntries);
    const cfgPath = resolveWeaponsCfgPath(lang);
    if (!cfgPath) {
      return {
        ok: false,
        path: null,
        count: merged.length,
        siteCount: siteEntries.length,
        error: 'weapons config directory not found on VPS',
      };
    }

    fs.writeFileSync(cfgPath, buildWeaponsCfgContent(merged), 'utf8');
    clearWsWeaponsAllowlistCache();
    console.log(
      `[weapons-cfg] wrote ${merged.length} entries (${siteEntries.length} from site) → ${cfgPath}`,
    );

    return {
      ok: true,
      path: cfgPath,
      count: merged.length,
      siteCount: siteEntries.length,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'sync failed';
    return {
      ok: false,
      path: null,
      count: 0,
      siteCount: 0,
      error: message,
    };
  }
}
